name: rebase-fork
on:
  schedule:
  - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 10
    - uses: justinrubek/rebase-upstream-action@main
      with:
        upstream: schizofox/schizofox
        branch: main
